name: build-publish-jdk11-dind-image
on:
  workflow_dispatch:


run-name: build-publish-sample-python-image
jobs:
  build-publish-jdk11-dind-image:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build and docker image with tag
      uses: docker/build-push-action@v6
      with:
        file: Dockerfile
        push: true
        tags: |
          ${{ secrets.DOCKERHUB_USERNAME }}/sample-python-image:latest
